Update versioning.yml

diff --git a/.github/workflows/versioning.yml b/.github/workflows/versioning.yml
--- a/.github/workflows/versioning.yml
+++ b/.github/workflows/versioning.yml
@@ -150,4 +150,32 @@ jobs:
           --arg title "Release: ${{ needs.version-tag.outputs.version }}" \
           --arg parentId "163998" \
           --arg value "$RELEASE_NOTES" \
-         
+          --arg gitCommitUrl "$GIT_COMMIT_URL" \
+          '{
+              "spaceId": $spaceId,
+              "status": $status,
+              "title": $title,
+              "parentId": $parentId,
+              "body": {
+              "representation": "wiki",
+              "value": $value
+              },
+              "gitCommitUrl": $gitCommitUrl
+          }'
+          )
+
+          echo "Payload: $payload"
+          response=$(curl --request POST \
+              --url 'https://agrim.atlassian.net/wiki/api/v2/pages' \
+              --user '${{ vars.CONFLUENCE_EMAIL }}:${{ secrets.CONFLUENCE_API_TOKEN }}' \
+              --header 'Accept: application/json' \
+              --header 'Content-Type: application/json' \
+              --data "$payload")
+          echo "Response: $response"
+          pageId=$(echo "$response" | jq -r '.id')
+          echo "Page ID: $pageId"
+          if [ "$pageId" == "null" ]; then
+            echo "Failed to create page"
+            exit 1
+          fi
+          echo "pageId=$pageId" >> $GITHUB_ENV
